// create new folder in workspace in this job where we clone the repo and copy the file to the desired location
def cloneRepositoryIfNotExists(String repoUrl, String branchName , String folderPath) {
    println 'Cloning repository...'
    println "Repository URL: ${repoUrl}"
    println "Branch Name: ${branchName}"
    println "Folder Path: ${folderPath}"

    // Ensure the target directory exists
    sh "mkdir -p ${folderPath}"

    // Check if git repository already exists then skip cloning
    if (fileExists("${folderPath}/.git")) {
        println "Git repository already exists in ${folderPath}. Skipping clone."
        return
    }

    // clone the repository
    dir(folderPath) {
        sh """
            git init
            git remote add origin ${repoUrl}
            git fetch origin ${branchName}:${branchName}
            git checkout ${branchName}
        """
        println 'Repository cloned successfully.'
    }

}

// function fetch latest changes
def renameBranchAndFetch(String branchName, String repoPath) {
    String backupBranchName = "backup_${branchName}"
    println "Renaming branch '${branchName}' to '${backupBranchName}' and fetching again..."
    println "Repository Path: ${repoPath}"

    // Use dir() to change directory context for all operations
    dir(repoPath) {
        sh """
            git branch -D ${branchName} || true
            git branch -m ${branchName} ${backupBranchName} || true
            git fetch origin ${branchName}:${branchName}
            git checkout ${branchName}
            git branch -D ${backupBranchName} || true
        """
        println 'Branch renamed and fetched successfully.'
        println 'Current branches:'
        sh 'git branch -a'
    }
}

def trackChangesOrCommit(String repoPath, String branchName) {
    println "Tracking changes for branch: ${branchName} in repo: ${repoPath}"

    println 'Change tracking logic not implemented yet.'
}

pipeline {
    agent any
    stages {
        stage('I18n Resource File Sync') {
            steps {
                script {
                    println '==============================='
                    println 'Starting I18n Resource File Sync Job'

                    def workspacePath = pwd()
                    println "Workspace path: ${workspacePath}"
                    def repoFolder = 'resourceBundle'
                    def repoPath = "${workspacePath}/${repoFolder}"
                    // create file in workspace to audit commit that processed
                    def auditFilePath = "${workspacePath}/i18n_audit.txt"
                    if (!fileExists(auditFilePath)) {
                        writeFile file: auditFilePath, text: ''
                    }

                    // The git.properties file is expected to be in the workspace.
                    println 'Checking for properties file: git.properties'

                    if (fileExists('git.properties')) {
                        println 'Found properties file: git.properties'

                        // Read and display the file contents
                        def fileContent = readFile('git.properties')
                        println 'File contents:'
                        println fileContent
                        def props = [:]
                        fileContent.split('\n').each { line ->
                            line = line.trim()
                            if (line && !line.startsWith('#')) {
                                def parts = line.split('=', 2)
                                if (parts.length == 2) {
                                    props[parts[0].trim()] = parts[1].trim()
                                }
                            }
                        }

                        def githubUrl = props.githubUrl
                        def filePath = props.filePath
                        def branchName = props.branchName

                        cloneRepositoryIfNotExists(githubUrl, branchName, repoPath)
                        renameBranchAndFetch(branchName, repoPath)
                    } else {
                        // Fail the build if the properties file is not found
                        error 'Properties file not found in workspace: git.properties'
                    }
                }
            }
        }
    }
}
